[theme]
# Base theme - will be overridden by custom CSS dynamically
primaryColor="#3B82F6"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8FAFC"
textColor="#1E293B"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "fast-nicedashboard.streamlit.app"
serverPort = 443
